name: Mlibc Compilation 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-22.04
    name: ${{ matrix.legs.MLIBC_COMPILE }}
    if: github.repository_owner == 'RT-Thread'
    strategy:
      fail-fast: false
      matrix:
       legs:
         -  MLIBC_COMPILE: "Mlibc Arm Compilation On Linux"
            MLIBC_TOOL_CHAIN: "sourcery-arm"
            ARCH: "arm"

         -  MLIBC_COMPILE: "Mlibc AArch64 Compilation On Linux"
            MLIBC_TOOL_CHAIN: "sourcery-aarch64"
            ARCH: "aarch64"

         -  MLIBC_COMPILE: "Mlibc RISCV32 Compilation On Linux"
            MLIBC_TOOL_CHAIN: "sourcery-rv32"
            ARCH: "riscv32"

         -  MLIBC_COMPILE: "Mlibc RISCV64 Compilation On Linux"
            MLIBC_TOOL_CHAIN: "sourcery-rv64"
            ARCH: "riscv64"

    steps:
      - uses: actions/checkout@v4
      - name: Install Arm ToolChains
        if: ${{ matrix.legs.MLIBC_TOOL_CHAIN == 'arm' && success() }}
        shell: bash
        run: |
           wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.3/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
           sudo tar xjf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -C /opt
           /opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc --version
           echo "MLIBC_TOOLCHAIN_CC=/opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc" >> $GITHUB_ENV
           echo "MLIBC_TOOLCHAIN_AR=/opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/arm-none-eabi-ar" >> $GITHUB_ENV

      - name: Install AArch64 ToolChains
        if: ${{ matrix.legs.MLIBC_TOOL_CHAIN == 'aarch64' && success() }}
        shell: bash
        run: |
           wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.6/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz
           sudo tar -xf gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz -C /opt
           /opt/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf/bin/aarch64-none-elf-gcc --version
           echo "MLIBC_TOOLCHAIN_CC=/opt/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf/bin/aarch64-elf-gcc" >> $GITHUB_ENV
           echo "MLIBC_TOOLCHAIN_AR=/opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/aarch64-elf-ar" >> $GITHUB_ENV

      - name: Install RV32 ToolChains
        if: ${{ matrix.legs.MLIBC_TOOL_CHAIN == 'rv32' && success() }}
        shell: bash
        run: |
           wget -q https://github.com/hpmicro/riscv-gnu-toolchain/releases/download/2022.05.15/riscv32-unknown-elf-newlib-multilib_2022.05.15_linux.tar.gz
           sudo tar zxf riscv32-unknown-elf-newlib-multilib_2022.05.15_linux.tar.gz -C /opt
           /opt/riscv32-unknown-elf-newlib-multilib/bin/riscv32-unknown-elf-gcc --version
           echo "MLIBC_TOOLCHAIN_CC=/opt/riscv32-unknown-elf-newlib-multilib/bin/riscv32-unknown-elf-gcc" >> $GITHUB_ENV
           echo "MLIBC_TOOLCHAIN_AR=/opt/riscv32-unknown-elf-newlib-multilib/bin/riscv32-unknown-elf-ar" >> $GITHUB_ENV

      - name: Install RV64 ToolChains
        if: ${{ matrix.legs.MLIBC_TOOL_CHAIN == 'rv64' && success() }}
        shell: bash
        run: |
           wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.4/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz
           sudo tar zxf riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz -C /opt
           /opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/riscv64-unknown-elf-gcc --version
           echo "MLIBC_TOOLCHAIN_CC=/opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/riscv64-unknown-elf-gcc" >> $GITHUB_ENV
           echo "MLIBC_TOOLCHAIN_AR=/opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/riscv64-unknown-elf-ar" >> $GITHUB_ENV

      - name: Mlibc Make Compile
        if: ${{ success() }}
        shell: bash
        env:
          ARCH : ${{ matrix.legs.ARCH }}
        run: |
          make